# Use an official Python base image
FROM python:3.11-slim

# Set working directory
WORKDIR /app

# Copy app code
COPY requirements_worker.txt .
RUN pip install -r requirements_worker.txt
COPY worker.py .
# Run the app
CMD ["python", "worker.py"]
