apiVersion: apps/v1
kind: Deployment
metadata:
  name: watcher
  namespace: rawdata
  labels:
    app: watcher
spec:
  replicas: 1
  selector:
    matchLabels:
      app: watcher
  template:
    metadata:
      labels:
        app: watcher
    spec:
      serviceAccountName: watcher-sa
      containers:
        - name: watcher
          image: adiganesh2004/watcher:latest  # Replace with your actual image tag if versioned
          imagePullPolicy: Always
          env:
            - name: MONGO_URL
              value: "mongodb://mongodb-service:27017"
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: PYTHONUNBUFFERED
              value: "1"
