apiVersion: apps/v1
kind: Deployment
metadata:
  name: watcher
  namespace: rawdata
spec:
  replicas: 1
  selector:
    matchLabels:
      app: watcher
  template:
    metadata:
      labels:
        app: watcher
    spec:
      serviceAccountName: watcher-sa
      containers:
      - name: watcher
        image: adiganesh2004/watcher:latest  # Replace with your DockerHub username and tag
        env:
        - name: MONGO_URL
          value: "mongodb://mongodb-service:27017"
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: PYTHONUNBUFFERED
          value: "1"
        imagePullPolicy: Always
