apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: rawdata-worker-scaler
spec:
  scaleTargetRef:
    name: rawdata-worker
  pollingInterval: 15        # seconds
  cooldownPeriod: 60         # seconds
  minReplicaCount: 2
  maxReplicaCount: 10
  triggers:
  - type: mongodb
    metadata:
      dbName: Mydb
      collection: rawdata_queue
      query: '{ "status": "unprocessed" }'
      queryValue: "5"  # Scale up if > 5 unprocessed records
    authenticationRef:
      name: mongo-trigger-auth

