# ServiceAccount for the operator
apiVersion: v1
kind: ServiceAccount
metadata:
  name: operator-sa
  namespace: rawdata
---
# ClusterRole with full permissions needed for the operator
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mongodbqueue-operator-role
rules:
  - apiGroups: ["yourdomain.com"]
    resources: ["mongodbqueues"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["create", "get", "list", "watch"]

  - apiGroups: [""]
    resources: ["pods", "events"]
    verbs: ["create", "get", "list", "watch"]

  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["get", "list", "watch"]
---
# Binding the ServiceAccount to the ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: mongodbqueue-operator-binding
subjects:
  - kind: ServiceAccount
    name: operator-sa
    namespace: rawdata
roleRef:
  kind: ClusterRole
  name: mongodbqueue-operator-role
  apiGroup: rbac.authorization.k8s.io
