# ServiceAccount for the MongoDBQueue Operator
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mongodbqueue-operator-sa
  namespace: rawdata
---
# ClusterRole granting necessary permissions to the Operator
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mongodbqueue-operator-role
rules:
  # Access to the MongoDBQueue custom resource
  - apiGroups: ["yourdomain.com"]
    resources: ["mongodbqueues"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

  # Permission to create and manage Kubernetes Jobs
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["get", "list", "watch", "create"]

  # Permission to access basic pod and event resources
  - apiGroups: [""]
    resources: ["pods", "events"]
    verbs: ["get", "list", "watch", "create"]

  # Permission to read CRD definitions (optional but helpful for introspection)
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["get", "list", "watch"]
---
# Bind the ServiceAccount to the ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: mongodbqueue-operator-binding
subjects:
  - kind: ServiceAccount
    name: mongodbqueue-operator-sa
    namespace: rawdata
roleRef:
  kind: ClusterRole
  name: mongodbqueue-operator-role
  apiGroup: rbac.authorization.k8s.io
