apiVersion: v1
kind: ServiceAccount
metadata:
  name: watcher-sa
  namespace: rawdata
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: watcher-role
  namespace: rawdata
rules:
  - apiGroups: ["yourdomain.com"]
    resources: ["mongodbqueues"]
    verbs: ["create", "get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: watcher-rolebinding
  namespace: rawdata
subjects:
  - kind: ServiceAccount
    name: watcher-sa
    namespace: rawdata
roleRef:
  kind: Role
  name: watcher-role
  apiGroup: rbac.authorization.k8s.io
