# crds/mongodbqueue.yaml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: mongodbqueues.yourdomain.com
spec:
  group: yourdomain.com
  names:
    kind: MongoDBQueue
    plural: mongodbqueues
    singular: mongodbqueue
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                recordId:
                  type: string
