apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: mongodbqueues.yourdomain.com
spec:
  group: yourdomain.com
  names:
    plural: mongodbqueues
    singular: mongodbqueue
    kind: MongoDBQueue
    shortNames:
      - mq
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          required:
            - spec
          properties:
            spec:
              type: object
              required:
                - recordIds
              properties:
                recordIds:
                  type: array
                  description: List of MongoDB record IDs to be processed.
                  items:
                    type: string
            status:
              type: object
              properties:
                state:
                  type: string
                  description: Current processing state (e.g., Pending, Processing, Completed).
                message:
                  type: string
                  description: Optional message for human-readable status.
