apiVersion: apps/v1
kind: Deployment
metadata:
  name: rawdata-operator
  namespace: rawdata
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rawdata-operator
  template:
    metadata:
      labels:
        app: rawdata-operator
    spec:
      serviceAccountName: operator-sa
      containers:
        - name: operator
          image: adiganesh2004/rawdata-operator:1.1     # <-- your Docker Hub image
          imagePullPolicy: Always
